### ISSUE TITLE
Should Wayland allow double buffering or just wait until the buffer is released.

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#41]
On Wayland, we need to wait for the server to release a wl_buffer before we can reuse it. This generally means clients will double buffer and track buffer age when rendering. However it would be most ideal to avoid double buffering if at all possible.

This probably means that softbuffer also needs a way to check if the buffer can be acquired to be rendered to if we run out of buffers to use.

**Comment by ids1024** [comment]
I guess an alternative to blocking would be to just drop the frame (have `set_buffer` do nothing if the back buffer hasn't been released)? But that could only work if the caller expects it to work that way, or it might not set a new buffer any time soon.

Maybe blocking until buffer release is best. While if the application were to drive its rendering based on a `frame` callback, this has no impact since the buffer would already be released.

**Comment by jackpot51** [comment]
I believe this is fixed by #55
