### ISSUE TITLE
Lifetime of `Context`

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/softbuffer#75]
I know this is not released yet, but after #64 `Context` and `Surface` were split.

How long is `Context` supposed to be kept alive? Does it need to stay alive as long as `Surface`, or can it be safely dropped while `Surface` is kept around and used?

**Comment by ids1024** [comment]
Anything from the `Context` that's still needed is reference counted, so the `Context` struct can be dropped.

Though the underlying `RawDisplayHandle` and `RawWindowHandle` must remain valid for the lifetime of the `Surface`, or its undefined behavior.

**Comment by daxpedda** [comment]
Thanks!

**Comment by kpreid** [comment]
I'd like to propose reopening this issue, as this could be specified more clearly in the documentation for everyone to see. The current safety documentation for `Surface::new` says:

> Ensure that the provided objects are valid to draw a 2D buffer to, and are valid for the lifetime of the Context

which could be interpreted as anything from @daxpedda's “stay alive as long as Surface” to the perverse “it doesn't matter if the handle stops being valid while you're still using the Surface, as long as you drop the Context first so its 'lifetime' has ended”. (And “the lifetime of” isn't probably what you mean either, since _the lifetime of_ the `&W` _reference_ will most likely end before the surface is done.)

(I also wish "the provided objects are valid to draw a 2D buffer to" was phrased as something that the author of a _cross-platform_ program finds actionable — what documentation should they read to know what it means? But that's not this issue.)

This is a little nitpicky, but I think that it's important to help users writing `unsafe` code by making it easy to understand what requirements they must uphold — or many of them will just give up and proceed sloppily.

**Comment by notgull** [comment]
This is now fixed as of #132
